* ゲームメカニクス おもしろくするためのゲームデザイン
** 第1章 ゲームメカニクスのデザイン
*** 概要
ゲームメカニクスは、ゲームの心臓部におけるルールであり、プロセスであり、データである。
どのように遊びが進行し、いつ何が起きて、勝利条件と敗北条件について定義している。
5種類のゲームメカニクスと、どのように一般的なビデオゲームで使われているかを紹介する。
ゲームデザインのプロセスの間で、度のタイミングでメカニクスをデザインしプロトタイプすべきかを説明。
3種類のプロトタイピング技法と、それぞれの長所と短所を説明。
*** 目的
ゲームメカニクスがなんのためにあり、そのデザインを考えるにはどうすべきかを、明確に理解する。
*** まとめ
ゲームメカニクスとは、ゲームの心臓部分の要素やプロセスだけでなく、そのプロセスを実行するために必要とされるデータまでを含んだ、明確に指定されたゲームのルール。
メカニクスには、継続的メカニクスと離散的メカニクスがある。
メカニクスは早い時期でデザインを開始する。メカニクスがなければ、プロトタイプの作成やプレイテストができないから。
メカニクスの中には、創発型ゲームプレイに大きく貢献する特定の構造を持つメカニクスがある。

*** ルールはゲームを定義する
ゲームの定義はさまざまだが、ほとんどに共通しているのは「ゲームの本質的なフィーチャー(特徴、機能)はルールである」ということ。
#+BEGIN_QUOTE
ゲームとは、架空のリアリティーという文脈の中で、最低1つの任意のおおきな目標を達成するために、参加者がルールに従って行動することで繰り広げられるプレイという行為の一種である。
-- Fundamentals of Game Design
#+END_QUOTE

#+BEGIN_QUOTE
ゲームとは、プレイヤーがルールを決められた人工的な対立に参加するシステムであり、定量化できる結果が生じる。
-- Rules of Play
#+END_QUOTE

#+BEGIN_QUOTE
ゲームとは、可変的かつ定量化できる結果を内包するルールベースのシステムである。
結果には対応する評価が存在し、プレイヤーは結果に影響を与えようと努力し、結果に対して感情的なつながりを持つ。
また、ゲームの終了結果が別のものに変換されることもある。
-- Half-Real, Video Games between Real Rules and Fictional Worlds
#+END_QUOTE

**** ゲームは予測できない
ゲームはある程度予測不可能であるべき。
ほとんどのゲームは3種類の要素が原因で、予測不可能性を作っている。
1. 偶然の要素
2. プレイヤーの選択
3. 複雑なルール(一つ一つのルールは単純でも、組み合わせると複雑になる場合が多い)

**** ルールからメカニクスへ

- ゲームルール - プレイヤーが認知している印刷された説明。
- ゲームメカニクス - ゲームルール＋十分詳細化されているが、テキストとして表示されていないもの。
  ex) モノポリーの不動産価格、チャンスカードの種類etc

となる。ゲームルールよりゲームメカニクスを使うことが好まれる。
最も影響力があり、ゲームの多くの側面に影響を与えるメカニクスをコアメカニクスと呼ぶ。
ex) マリオにおける重力
ただし、ゲームデザイナによって、同じゲームでも何をコアと受け取るかは違う。
メカニクスは媒体に依存しないので、1つのゲームのメカニクスを作ったあと、異なる媒体でそのゲームをつくることができる。

**** 5種類のメカニクス

***** 物理
ゲーム世界における物理を定義する。これは、ジャンプ中に方向が変えられるなどの非ニュートン的な挙動ができてもよい。

***** 内部経済
ゲーム要素の収集、消費、交換といった取引のメカニクス。
典型的には、リソースと用意に認識されるアイテムだが、スキルポイントなど抽象的なものも扱うことができる。
***** 進行型のメカニズム
プレイヤの進行状況は、特定のエリアへの立ち入りをブロックしたりアンロックしたりするメカニクスによりコントロールされている。
レバー、スイッチなどが典型的な例。
***** 戦術的な操作
攻撃や守備の優位性のために、マップ上のゲームユニットに配置を行うメカニクス。
チェスなどのボードゲームが典型的な例。
***** 社会的インタラクション
友人にプレゼントを贈ったり、招待などの方法で交流を持つことに対してリワードを提供するメカニクス。

*** 離散的メカニクス vs 継続的メカニクス
離散的メカニクスのほうが、大きなイノベーションを起こしやすい。

継続的メカニクス - 毎秒大量の計算を伴うリアルタイム処理で実装。ゲーム内の物理処理を実装するために用いられる。コントロールの小さな誤差が、大きな結果の差につながる
離散的メカニクス - 0か1かのように大きな違いが出るようなもの。
***  メカニクスとゲームデザインのプロセス
ゲームデザインの方法はゲーム会社の数だけある。

**** ゲームデザインプロセスの概要

1. コンセプトステージ
   この段階の結果は、ビジョンドキュメントやゲームトリートメントにまとめられる。
   以下の重要なコンセプトを決定する。これらはその後のデザインプロセスで変更すべきでない。
   - ゲームの基本的なアイデア
   - ターゲットとなるユーザー
   - プレイヤーの役割
   また、このステージが完了するまでは、本番用のデザインを始めるべきではない。
2. 遂行ステージ
   - ゲームメカニクスとレベルの作成
   - ストーリーの起草
   - アートアセットの作成

3. チューニングステージ
   - 仕様の凍結辞典ではじまる。
   - ここまで作り上げたものを作りこむ
   - 変更はしない
   - 開発期間全体の1/3から半分を占める
**** 早い段階でのメカニクスデザイン
推敲ステージの早い段階でゲームメカニクスに取り組み始める。
- ゲームプレイはゲームメカニクスから発現する。ルールを見ただけで、そのゲームが面白いかどうかを見極めるのは困難。
- ゲームメカニクスは複雑であり、ゲームプレイはシステム上のデリケートなバランスに依存している。後でフィーチャーの追加、変更が加わればバランスが崩れる。
*** プロトタイピング技法
ゲームデザイナが使用する一般的なプロトタイプ技法
**** ソフトウェアプロトタイピング
- 利点
  バグだらけ、アート部分が未完成でも、いい指摘ができること
- 欠点
  他のプロトタイピング技法に比べ、作成に時間がかかる
ゲームデザイナがかならず設定を変更できるようにしておく。
ゲームデザイナは設定のバランスをいじりながらプレイをする。
**** ペーパープロトタイピング
コンピュータによる演算を用いない、目的のゲームに似せた卓上ゲーム。
アクション、シューティングなど、コンピュータ演算を必要としないのであれば、コンセプトからボードゲームが作れる。
- 利点
  素早く作れる
  カスタマイズ可能である
- 欠点
  テストプレイヤの参加が難しい(ルールの説明が難しい)
  すべてのメカニクスがうまくボードゲームで再現できるわけではない。
ゲーム内経済や、ゲームの進行を制御するメカニクスをデザインするときに用いる
**** フィジカルプロトタイピング
実際に体験してみる。FPSゲームの際に、実際にシューティングをやってみる。
- 利点
  準備の手間が少ない
  高速で柔軟性が高い
- 欠点
  テストプレイヤの参加が難しい(ルールの説明が難しい)
  すべてのメカニクスがうまくボードゲームで再現できるわけではない。
*** プロトタイプの種類1
1. 高再現性プロトタイプ
2. 低再現性プロトタイプ
   通常、最終製品につかわれているものとは違う技術を用い、とりあえず動くものをつくる。
*** プロトタイプの種類2
プロジェクト全体の層構造
- アート／アニメーションアセット
- オーディオアセット
- ユーザーインターフェースコード
- コアメカニクスコード

1. バーティカルスライス
   ゲームのフィーチャーの1つもしくは少数を実装するために必要な全要素(コード、アート、オーディオetc)を備えたプロトタイプ。
   ゲームが未完成でも、各ゲームプレイのテストが行え、ゲームの雰囲気の把握ができる。
2. ホリゾンタルスライス
   ゲームの1部分だけで構成されるプロトタイプ。その他の要素を含まない。

*** プロトタイプのフォーカスと、順番
1. 技術デモ
   最も難しく、斬新な部分が技術的に可能かを確認する。
2. ゲーム内経済
   ペーパープロトタイピングで再現しながら確認する。
   確認事項は以下のもの
   - ゲームのバランスはとれているか？
   - 必ず勝てる戦略、絶対有利な戦略がないか？
   - プレイヤーが楽しめる選択肢が用意されているか？
   - プレイヤーは選択の結果を十分に予測できるか？
3. インターフェースと操作体系
  プレイヤーがゲーム要素や、インタラクションをひととおり試す。
   - プレイヤーは提供されたアクションを正確に実行できるか？
4. チュートリアル
  ゲーム開発の後半に行う。
   - プレイヤーはゲームを理解しているか？どのようにゲームをプレイすべきか知っているか？


** 第2章 創発型と進行型
** 第3章 複雑系と創発型の構造
** 第4章 内部経済
** 第5章 マキネーション
** 第6章 一般的なメカニズム
** 第7章 デザインパターン
** 第8章 ゲームのシミュレーションとバランスとり
** 第9章 経済の構築
** 第10章 レベルデザインとメカニクスの統合
** 第11章 進行型のメカニズム
** 第12章 意味のあるメカニクス
** 付録A マキネーションクイックリファレンス
** 付録B デザインパターンライブラリ

** 付録まとめ

*** Kyle Gablerの基調講演まとめ
http://www.youtube.com/watch?v=aW6vgW8wc6c

**** Adjust expectation プレイヤーの期待に応える
**** Create Low barrior to Entry やりはじめの15秒に面白さを詰め込む
**** Feel Something 感情に訴える
**** Make the TOY First 先におもちゃをつくろう
**** shh... 音楽を考える
**** harmony 全体の調和を意識する
**** Never Fall in Love あまりゲームに愛と関心をもたない
*** おすすめのペーパープロトタイピングキット
- 背面の色がことなる、ほぼおなじカードデッキ(トランプ) 2セット
- 小さなノート、ペン
- トークン
- いくつかのダイス。
- 付箋紙
- 75x125mmの白紙カード
